# Generated by Django 3.1.3 on 2024-05-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='like',
            new_name='likes',
        ),
    ]
