"""empty message

Revision ID: 0f743c1f0e3a
Revises: 20744a0454e5
Create Date: 2024-04-27 09:25:52.956893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f743c1f0e3a'
down_revision = '20744a0454e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_product_unique', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_user', schema=None) as batch_op:
        batch_op.drop_constraint('user_product_unique', type_='unique')

    # ### end Alembic commands ###
